### PR TITLE
added play28, up sbt(1.3.10) and scala(2.13.2)

### PR DESCRIPTION
**Pull request by ghost**
## Summary
Completes feature #33 
Related tickets: #33 
### Tests
- [OK] All tests passes

### CODE REVIEW

**Comment by hhandoko** [comment]
Thanks for your PR!

**Comment by tolomaus** [comment]
Hi Herdy, 

Could you create a release for Play 2.8?

Many thanks

**Comment by hhandoko** [comment]
Hi @tolomaus , I just checked and there is an issue with cross-publishing for Play 2.8 on Scala 2.12 (due to the use of `LazyList`). I will need to look into this first.

**Comment by hhandoko** [comment]
Play 2.8 version has been released.

**Comment by tolomaus** [comment]
Cool many thanks!

And btw thanks for maintaining this excellent library!

**Comment by hhandoko** [comment]
No worries, glad you find it useful!

**Pull request merged**
